<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>z80</string>
    </array>
    <key>name</key>
    <string>Z80 Assembly</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\s*;.*$</string>
            <key>name</key>
            <string>comment.line</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*(ld|ldi|ldd|ldh|push|pop|add|adc|sub|sbc|and|or|xor|cp|inc|dec|daa|cpl|rlca|rla|rrca|rra|rlc|rl|rrc|rr|sla|swap|sra|srl|bit|res|set|ccf|scf|nop|halt|stop|di|ei|jp|jr|call|ret|reti|rst)\b</string>
            <key>name</key>
            <string>keyword.other.mnemonic</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\$[0-9a-fA-F]+</string>
            <key>name</key>
            <string>constant.numeric.hex</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(MACRO|ENDM|IF|ENDC|REPT|ENDR|DB|DW|DS|INCLUDE|INCBIN|SECTION|EQU)\b</string>
            <key>name</key>
            <string>keyword.control.directive</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(a|b|c|d|e|h|af|bc|de|hl|sp)\b</string>
            <key>name</key>
            <string>support.class.z80</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.class.z80</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.z80</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(\.?[a-zA-Z_][a-zA-Z_0-9\\@]*)\s*(\:)\s*$</string>
            <key>name</key>
            <string>meta.label.z80</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.z80</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*([a-zA-Z_][a-zA-Z_0-9\\@]*)\b</string>
            <key>name</key>
            <string>meta.command.z80</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.z80</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b([a-zA-Z_][a-zA-Z_0-9\\@]*)\b</string>
            <key>name</key>
            <string>meta.identifier.z80</string>
        </dict>
        <dict>
            <key>match</key>
            <string>!|%|&amp;|\*|\-|\+|~|/|\^|==|=|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;|&amp;&amp;|\|\||\||\.?</string>
            <key>name</key>
            <string>keyword.operator.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>meta.brace.curly.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>meta.brace.round.js</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>meta.brace.square.js</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.js</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.js</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.js</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.js</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.js</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.js</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
                    <key>name</key>
                    <string>constant.character.escape.js</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.z80</string>
    <key>uuid</key>
    <string>3A406674-FF3F-4495-BF50-C159AC0245B9</string>
</dict>
</plist>
